name: Windows

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Build
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g yarn
    - run: yarn
    - run: yarn run make --targets "zip,squirrel"
    - uses: actions/upload-artifact@v4
      with:
        name: dz-windows
        path: |
          out/make/*
